services:

  # app service for Go API
  api:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: e-learning-api
    env_file: 
      - .env
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./src:/app
    depends_on:
      - db
    command: ['air', '-c', '.air.toml'] # Use air for hot reloading
  
  # database service for PostgreSQL
  db: 
    image: postgres:17-alpine
    container_name: e-learning-db
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  # pgadmin service for database management
  pgadmin: 
    image: dpage/pgadmin4:latest
    container_name: e-learning-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
      
volumes:
  pgdata: